{ config, pkgs, ... }:

{
  imports =
    [ 
      # Include the results of the hardware scan.
      # It should be generated by self.
      ../hardware-configuration.nix
    ];

  # Bootloader.
  # Bootloader.
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sdb";
  boot.loader.grub.useOSProber = true;
  boot.tmp.useTmpfs = true;
  boot.tmp.tmpfsSize = "25%";

  # This is for OBS Virtual Cam Support - v412loopback setup
  boot.kernelModules = [ "v4l2loopback" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.v4l2loopback ];

  networking.hostName = "pc_nvidia"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Enable networking
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "Europe/Moscow";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "ru_RU.UTF-8";
    LC_IDENTIFICATION = "ru_RU.UTF-8";
    LC_MEASUREMENT = "ru_RU.UTF-8";
    LC_MONETARY = "ru_RU.UTF-8";
    LC_NAME = "ru_RU.UTF-8";
    LC_NUMERIC = "ru_RU.UTF-8";
    LC_PAPER = "ru_RU.UTF-8";
    LC_TELEPHONE = "ru_RU.UTF-8";
    LC_TIME = "ru_RU.UTF-8";
  };

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.docnite = {
    isNormalUser = true;
    description = "docnite";
    shell = pkgs.zsh;
    extraGroups = [ "networkmanager" "wheel" "docker" ];
    packages = with pkgs; [];
  };

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;
  #nixpkgs.config.permittedInsecurePackages = [
  #  "python3.12-youtube-dl-2021.12.17"
  #];

  # Enable the Flakes feature and the accompanying new nix cmd tools
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  
  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [

   luanti

   zip

   # Terminal shell
   nushell

   # Cow saying 
   cowsay
    
   # YT Music 
   youtube-music

   # GTK Theme changer 
   themechanger

   # Font manager 
   font-manager

   # Based editor and another tools
   vim wget curl cmatrix

   # Search packages
   nix-search-cli

   # Terminal emulator
   kitty starship

   # Archiver
   kdePackages.ark

   # Browser
   firefox-bin

   # Status bar and widgets
   eww waybar

   # Editor, better than VIM
   neovim zed-editor neovide
   vscode # ONLY FOR C#/Java projects with shitty LSP, because i can't run omnisharp in zed and nvim. So, it might better way to program on C# with intellisense

   # System staff
   playerctl ffmpeg pkg-config brightnessctl

   # Script runtime / Interpreter
   lua python3 mruby deno

   # Windows emulation
   wineWowPackages.stable

   # Compilers
   gcc gnumake

   # Another packages
   noto-fonts-color-emoji rar nh
   networkmanagerapplet material-icons wl-clipboard
   btop unzip unrar ripgrep killall bat tree
   lxqt.lxqt-policykit glib ydotool

   # Screen recorder
   obs-studio wl-screenrec

   # Notifications
   dunst libnotify

   # Video wallpaper
   mpvpaper

   # Hypr's
   hyprpaper hyprpicker hypridle hyprlock hyprcursor

   # Application launcher
   rofi-wayland rofi-bluetooth rofi-emoji-wayland
   rofi-vpn rofi-obsidian rofi-power-menu

   # File manager
   yazi

   # Set monitors
   wdisplays

   # Screenshots
   flameshot #swappy

   # Doc viewer
   zathura

   # Audio controller
   pavucontrol

   # Video/Audio playback
   vlc mpv cmus

   # Image viewer
   loupe #gwenview

   # LSP
   vscode-langservers-extracted nixd rust-analyzer
   lua-language-server hyprls

   # Cursor theme
   bibata-cursors

   # Screenshots
   grim slurp

   # Polkit
   polkit_gnome

   # gsettings
   gsettings-desktop-schemas

   # GTK Themes 
   pkgs.adwaita-icon-theme
   pkgs.gnome-themes-extra
   gtk3 gtk4
  ];

  environment.sessionVariables = {
    POLKIT_AUTH_AGENT = "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1";
    GSETTINGS_SCHEMA_DIR = "${pkgs.gsettings-desktop-schemas}/share/gsettings-schemas/${pkgs.gsettings-desktop-schemas.name}/glib-2.0/schemas";
  };

  # Install system fonts for the user.
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    nerd-fonts._0xproto
  ];

  # Theme QT -> GTK
  qt = {
    enable = true;
    platformTheme = "gnome";
    style = "adwaita-dark";
  };

  # Enable ZSH 
  programs.zsh = {
    enable = true;
    enableCompletion = true;
    autosuggestions.enable = true;
    syntaxHighlighting.enable = true; 
  };

  # Enable Hyprland as WM.
  programs.hyprland = {
    enable = true;
    xwayland.enable = true;
  };

  # Enable git as powerful tool.
  programs.git = {
    enable = true;
  };

  # dconf :woozy:
  programs.dconf = {
    enable = true;
    #settings."org/gnome/desktop/interface".color-scheme = "prefer-dark";
  };

  programs.seahorse.enable = true;
  programs.fuse.userAllowOther = true;

  # File manager
  programs.thunar = {
    enable = true;
    plugins = with pkgs.xfce; [
      thunar-archive-plugin
      thunar-volman
    ];
  };

  # Theme shell (starship)
  # programs.starship.enable = true;

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  programs.mtr.enable = true;
  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
  };

  # Enable nix-ld for running dynamicly libraries
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      alsa-lib at-spi2-atk at-spi2-core atk cairo
      cups curl dbus expat fontconfig freetype fuse3
      gdk-pixbuf glib gtk3 icu libGL libappindicator-gtk3
      libdrm libglvnd libnotify libpulseaudio libunwind
      libusb1 libuuid libxkbcommon libxml2 mesa nspr nss
      openssl pango pipewire stdenv.cc.cc systemd
      vulkan-loader xorg.libX11 xorg.libXScrnSaver
      xorg.libXcomposite xorg.libXcursor xorg.libXdamage
      xorg.libXext xorg.libXfixes xorg.libXi xorg.libXrandr
      xorg.libXrender xorg.libXtst xorg.libxcb xorg.libxkbfile
      xorg.libxshmfence zlib
    ];
  };

  # Virtual manager for VM
  programs.virt-manager.enable = true;

  # Enable virtualization
  virtualisation.libvirtd.enable = true;

  # List environment variables:

  # Set the default system editor.
  environment.variables.EDITOR = "vim";

  # Enable OZONE for running electron apps under wayland.
  environment.sessionVariables.NIXOS_OZONE_WL = "1";

  # List services that you want to enable:

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # Login screen manager
  services.displayManager.ly.enable = true;

  services.libinput.enable = true;

  # services.xserver.enable = true;
  # For AMD
  # services.xserver.videoDrivers = [ "amdgpu" ];

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  services.fstrim.enable = true;

  xdg.portal = {
    enable = true;
    wlr.enable = true;
    extraPortals = [
      pkgs.xdg-desktop-portal-gtk
      pkgs.xdg-desktop-portal
    ];
    configPackages = [
      pkgs.xdg-desktop-portal-gtk
      pkgs.xdg-desktop-portal-hyprland
      pkgs.xdg-desktop-portal
    ];
  };

  # Polkit from old config
  systemd.user.services.polkit-gnome-authentication-agent-1 = {
    description = "polkit-gnome-authentication-agent-1";
    wantedBy = [ "graphical-session.target" ];
    wants = [ "graphical-session.target" ];
    after = [ "graphical-session.target" ];
    serviceConfig = {
      Type = "simple";
      ExecStart = "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1";
      Restart = "on-failure";
      RestartSec = 1;
      TimeoutStopSec = 10;
    };
  };



  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    jack.enable = true;
  };

  services.gvfs.enable = true;

  services.tumbler.enable = true;

  # Enable the gnome-keyring secrets vault.
  services.gnome.gnome-keyring.enable = true;

  # Bluetooth manager
  services.blueman.enable = true;

  services.pulseaudio.enable = true;

  # GAOMON s620 tablet pen resolution fix
  services.udev.extraHwdb = ''
  evdev:input:b0003v256Cp006F*
    EVDEV_ABS_00=::210
    EVDEV_ABS_01=::323
    EVDEV_ABS_35=::210
    EVDEV_ABS_36=::323
  '';

  # Enable flatpak
  services.flatpak.enable = true;
  systemd.services.flatpak-repo = {
    wantedBy = [ "multi-user.target" ];
    path = [ pkgs.flatpak ];
    script = ''
      flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    '';
  };

  # List hardware features:

  hardware.bluetooth.enable = true;

  hardware.bluetooth.powerOnBoot = true;

  # OpenGL
  hardware.graphics = {
    enable = true;
  };

  # Load nvidia driver for Xorg and Wayland
  services.xserver.videoDrivers = ["nvidia"];

  hardware.nvidia = {

    # Modesetting is required.
    modesetting.enable = true;

    # Nvidia power management. Experimental, and can cause sleep/suspend to fail.
    # Enable this if you have graphical corruption issues or application crashes after waking
    # up from sleep. This fixes it by saving the entire VRAM memory to /tmp/ instead 
    # of just the bare essentials.
    powerManagement.enable = false;

    # Fine-grained power management. Turns off GPU when not in use.
    # Experimental and only works on modern Nvidia GPUs (Turing or newer).
    powerManagement.finegrained = false;

    # Use the NVidia open source kernel module (not to be confused with the
    # independent third-party "nouveau" open source driver).
    # Support is limited to the Turing and later architectures. Full list of 
    # supported GPUs is at: 
    # https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus 
    # Only available from driver 515.43.04+
    # Currently alpha-quality/buggy, so false is currently the recommended setting.
    open = false;

    # Enable the Nvidia settings menu,
	# accessible via `nvidia-settings`.
    nvidiaSettings = true;

    # Optionally, you may need to select the appropriate driver version for your specific GPU.
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  # List some security features:

  security.rtkit.enable = true;

  # Enable polkit
  security.polkit.enable = true;

  security.polkit.extraConfig = ''
    polkit.addRule(function(action, subject) {
      if (
        subject.isInGroup("users")
          && (
            action.id == "org.freedesktop.login1.reboot" ||
            action.id == "org.freedesktop.login1.reboot-multiple-sessions" ||
            action.id == "org.freedesktop.login1.power-off" ||
            action.id == "org.freedesktop.login1.power-off-multiple-sessions"
          )
        )
      {
        return polkit.Result.YES;
      }
    })
  '';

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "24.11"; # Did you read the comment?

}
